/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/Tabs/ConfigItem/Address.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    Config: typeof import('./src/components/Tabs/Config.vue')['default']
    ConfigItem: typeof import('./src/components/Tabs/ConfigItem/ConfigItem.vue')['default']
    Filter: typeof import('./src/components/Tabs/Filter.vue')['default']
    FormItem: typeof import('./src/components/Tabs/ConfigItem/Form/FormItem.vue')['default']
    FormSelect: typeof import('./src/components/Tabs/ConfigItem/Form/FormSelect.vue')['default']
    JobCard: typeof import('./src/components/JobCard.vue')['default']
    JobCards: typeof import('./src/components/JobCards.vue')['default']
    Log: typeof import('./src/components/Menu/Log.vue')['default']
    Logs: typeof import('./src/components/Tabs/Logs.vue')['default']
    SalaryRange: typeof import('./src/components/Tabs/ConfigItem/Form/SalaryRange.vue')['default']
    Statistics: typeof import('./src/components/Tabs/Statistics.vue')['default']
    Store: typeof import('./src/components/Menu/Store.vue')['default']
    UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
    UInputTags: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue')['default']
    ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/overrides/none/Link.vue')['default']
    UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTheme: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Theme.vue')['default']
    Version: typeof import('./src/components/Menu/Version.vue')['default']
  }
}

// For TSX support
declare global {
  const Address: typeof import('./src/components/Tabs/ConfigItem/Address.vue')['default']
  const Alert: typeof import('./src/components/Alert.vue')['default']
  const Config: typeof import('./src/components/Tabs/Config.vue')['default']
  const ConfigItem: typeof import('./src/components/Tabs/ConfigItem/ConfigItem.vue')['default']
  const Filter: typeof import('./src/components/Tabs/Filter.vue')['default']
  const FormItem: typeof import('./src/components/Tabs/ConfigItem/Form/FormItem.vue')['default']
  const FormSelect: typeof import('./src/components/Tabs/ConfigItem/Form/FormSelect.vue')['default']
  const JobCard: typeof import('./src/components/JobCard.vue')['default']
  const JobCards: typeof import('./src/components/JobCards.vue')['default']
  const Log: typeof import('./src/components/Menu/Log.vue')['default']
  const Logs: typeof import('./src/components/Tabs/Logs.vue')['default']
  const SalaryRange: typeof import('./src/components/Tabs/ConfigItem/Form/SalaryRange.vue')['default']
  const Statistics: typeof import('./src/components/Tabs/Statistics.vue')['default']
  const Store: typeof import('./src/components/Menu/Store.vue')['default']
  const UAccordion: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
  const UAlert: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Alert.vue')['default']
  const UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UAvatar: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
  const UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCheckbox: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
  const UDropdownMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
  const UFieldGroup: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FieldGroup.vue')['default']
  const UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
  const UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
  const UIcon: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
  const UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const UInputNumber: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue')['default']
  const UInputTags: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue')['default']
  const ULink: typeof import('./node_modules/@nuxt/ui/dist/runtime/vue/overrides/none/Link.vue')['default']
  const UModal: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
  const UPopover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
  const UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  const USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
  const USkeleton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
  const UTable: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
  const UTabs: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
  const UTheme: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Theme.vue')['default']
  const Version: typeof import('./src/components/Menu/Version.vue')['default']
}